services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: i2i_oracle_xe
    environment:
      - ORACLE_PASSWORD=i2iPassword123
    ports:
      - "1522:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
