services:
  oracle-db:
    image: gvenzl/oracle-xe:slim
    container_name: i2i_oracle_db
    environment:
      - ORACLE_PASSWORD=oracle
    ports:
      - "1521:1521"
    volumes:
      - ./init-scripts:/container-entrypoint-initdb.d/
    restart: unless-stopped